FROM golang:alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o main ./cmd/autoscaler/main.go

FROM alpine:latest
RUN apk add --no-cache docker-cli
WORKDIR /app
COPY --from=builder /app/main .
CMD ["./main"]
